#!/usr/bin/env python

from pynput.mouse import Button, Controller
import time
import random

mouse = Controller()

#mouse.position = (1130, 595)
#time.sleep(2)
#mouse.click(Button.left, 1)
trips = 0
while True:
 #break
 mouse.position = (random.randint(1280, 1300), random.randint(340, 360))
 time.sleep(1)
 mouse.click(Button.left, 2)
 time.sleep(random.randint(2,3))
 mouse.position = (random.randint(1560, 1565), random.randint(370, 375))
 time.sleep(1)
 mouse.click(Button.left, 1)
 time.sleep(1)
 mouse.position = (random.randint(990, 995), random.randint(140, 145))
 time.sleep(1)
 mouse.click(Button.left, 3)
 time.sleep(1)
 mouse.position = (random.randint(1385, 1395), random.randint(60, 70))
 time.sleep(1)
 mouse.click(Button.left, 1)
 time.sleep(1)
 mouse.position = (random.randint(1510, 1515), random.randint(370, 375))
 time.sleep(1)
 mouse.click(Button.left, 1)
 time.sleep(1)
 mouse.position = (random.randint(1560, 1565), random.randint(370, 375))
 time.sleep(1)
 mouse.click(Button.left, 1)
 time.sleep(1)
 mouse.position = (random.randint(1010, 1030), random.randint(585, 595))
 time.sleep(1)
 mouse.click(Button.left, 1)
 time.sleep(48)
